language: python
# Define language

after_success:
  - bash <(curl -s https://codecov.io/bash)
  # Sends coverage reports to codecov
# Define actions after successful build

python:
#  - "3.4"
#  - "3.5"
  - "3.6"      # current default Python on Travis CI
#  - "3.7"
#  - "3.8"
#  - "3.8-dev"  # 3.8 development branch
#  - "nightly"  # nightly build
# Specify versions of language to test


install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Installing conda
  
  - conda info -a
  # Useful for debugging any issues with conda

  - conda env create --file pseudo-it.yml
  - conda activate pseudo-it
  # Loading the pseudo-it conda environment

  - pip install coverage
  # Installing coverage for coverage reports for codecov
# Install dependencies

# command to run tests
script:
  - coverage run pseudo_it.py --version
  - coverage run pseudo_it.py --depcheck
  - coverage run pseudo_it.py -ref example-data/example.fa -pe1 example-data/example.pe1.fq.gz -pe2 example-data/example.pe2.fq.gz -o example-data/example-out/ -tmp tmp-pi-out -i 2 -p 8 --dryrun
  - coverage run pseudo_it.py -ref example-data/example.fa -pe1 example-data/example.pe1.fq.gz -pe2 example-data/example.pe2.fq.gz -o example-data/example-out/ -tmp tmp-pi-out -i 2 -p 8 --overwrite  
# Tests to run